-- ==================================================================================================================================================================== 
-- PROJECT TITLE : WheelsOnDemand: Enterprise Vehicle Rental Management & Fleet Intelligence Engine
-- DESCRIPTION   : Relational database architecture optimizing fleet utilization, asset depreciation tracking, and multi-tier revenue analytics.
-- AUTHOR        : Akash Kumar
-- ROLE          : Data / SQL Analyst Portfolio Project
-- DATABASE      : PostgreSQL (pgAdmin 4)
-- ENVIRONMENT   : Production Grade Transactional Schema
-- ====================================================================================================================================================================

-- --------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- SCRIPT CAPABILITIES: Relational table initialization (DDL), primary/foreign key mapping, multi-table JOIN metrics, and relational business aggregations.
-- --------------------------------------------------------------------------------------------------------------------------------------------------------------------

--Q1.Display all vehicles that are currently Available.

SELECT 
    *
FROM 
    VEHICLE
WHERE 
    Status = 'Available';

--Q2.Display all Cars with their vehicle name, brand and rent per day.

SELECT 
    Vehicle_Name,
    Brand,
    Rent_Per_Day
FROM 
    VEHICLE
WHERE 
    Vehicle_Type = 'Car';

--Q3.Display all Bikes whose rent per day is greater than ₹1,000.

SELECT 
    *
FROM 
    VEHICLE
WHERE 
    Vehicle_Type = 'Bike' 
    AND Rent_Per_Day > 1000;

--Q4.Display customers whose age is between 25 and 40.

SELECT 
    *
FROM 
    CUSTOMER
WHERE 
    Age BETWEEN 25 AND 40;

--Q5.Display all bookings where the payment status is Pending.

SELECT 
    *
FROM 
    BOOKING
WHERE 
    Payment_Status = 'Pending';

--Q6.Display the customer name, vehicle name, start date and end date for every booking.

SELECT 
    c.Customer_Name,
    v.Vehicle_Name,
    b.Start_Date,
    b.End_Date
FROM 
    BOOKING b
JOIN 
    CUSTOMER c ON b.CID = c.CID
JOIN 
    VEHICLE v ON b.VID = v.VID;

--Q7.Display customer name, phone number, vehicle name and bill amount for all bookings.

SELECT 
    c.Customer_Name,
    c.Phone,
    v.Vehicle_Name,
    b.Bill_Amount
FROM 
    BOOKING b
JOIN 
    CUSTOMER c ON b.CID = c.CID
JOIN 
    VEHICLE v ON b.VID = v.VID;

--Q8.Display all bookings for Cars along with customer details.

SELECT 
    b.BID,
    b.Booking_Date,
    b.Bill_Amount,
    v.Vehicle_Name,
    v.Brand,
    c.Customer_Name,
    c.Phone
FROM 
    BOOKING b
JOIN 
    VEHICLE v ON b.VID = v.VID
JOIN 
    CUSTOMER c ON b.CID = c.CID
WHERE 
    v.Vehicle_Type = 'Car';

--Q9.Display all customers who have made at least one booking.

SELECT DISTINCT
    c.CID,
    c.Customer_Name,
    c.Phone
FROM 
    CUSTOMER c
JOIN 
    BOOKING b ON c.CID = b.CID;

--Q10.Display all vehicles that have been booked at least once.

SELECT DISTINCT
    v.VID,
    v.Vehicle_Name,
    v.Vehicle_Type,
    v.Brand
FROM 
    VEHICLE v
JOIN 
    BOOKING b ON v.VID = b.VID;

--Q11.Find the total rental revenue generated by the company.

SELECT 
    SUM(Bill_Amount) AS total_rental_revenue
FROM 
    BOOKING;

--Q12.Find the average booking bill.

SELECT 
    ROUND(AVG(Bill_Amount), 2) AS average_booking_bill
FROM 
    BOOKING;

--Q13.Find the highest booking bill.

SELECT 
    MAX(Bill_Amount) AS highest_booking_bill
FROM 
    BOOKING;

--Q14.Find the total number of bookings.

SELECT 
    COUNT(*) AS total_bookings_count
FROM 
    BOOKING;

--Q15.Find the total revenue generated from Cars and Bikes separately.

SELECT 
    v.Vehicle_Type,
    SUM(b.Bill_Amount) AS total_segment_revenue
FROM 
    BOOKING b
JOIN 
    VEHICLE v ON b.VID = v.VID
GROUP BY 
    v.Vehicle_Type;

--Q16.Find the number of bookings made by each customer.(Display:Customer_Name,Number_of_Bookings).

SELECT 
    c.Customer_Name,
    COUNT(b.BID) AS Number_of_Bookings
FROM 
    CUSTOMER c
JOIN 
    BOOKING b ON c.CID = b.CID
GROUP BY 
    c.Customer_Name
ORDER BY 
    Number_of_Bookings DESC;

--Q17.Find the total amount spent by each customer.Display customers in descending order of total spending.

SELECT 
    c.Customer_Name,
    SUM(b.Bill_Amount) AS total_amount_spent
FROM 
    CUSTOMER c
JOIN 
    BOOKING b ON c.CID = b.CID
GROUP BY 
    c.Customer_Name
ORDER BY 
    total_amount_spent DESC;

--Q18.Find the number of bookings for each vehicle.(Display:Vehicle_Name,Number_of_Bookings).

SELECT 
    v.Vehicle_Name,
    COUNT(b.BID) AS Number_of_Bookings
FROM 
    VEHICLE v
JOIN 
    BOOKING b ON v.VID = b.VID
GROUP BY 
    v.Vehicle_Name
ORDER BY 
    Number_of_Bookings DESC;

--Q19.Find vehicle types having more than 3 bookings.

SELECT 
    v.Vehicle_Type,
    COUNT(b.BID) AS total_bookings
FROM 
    VEHICLE v
JOIN 
    BOOKING b ON v.VID = b.VID
GROUP BY 
    v.Vehicle_Type
HAVING 
    COUNT(b.BID) > 3;

--Q20.Find the top 3 customers who have generated the highest rental revenue.(Display:Customer_Name,Number_of_Bookings,Total_Spending).

SELECT 
    c.Customer_Name,
    COUNT(b.BID) AS Number_of_Bookings,
    SUM(b.Bill_Amount) AS Total_Spending
FROM 
    CUSTOMER c
JOIN 
    BOOKING b ON c.CID = b.CID
GROUP BY 
    c.Customer_Name
ORDER BY 
    Total_Spending DESC
LIMIT 3;